### ISSUE TITLE
The js deploy file not executing.

### ISSUE THREAD

**Issue by cyrus19901** [SeanAvery/Tribe_Exchange-TX#1]
Hi ,

I have been looking at the code and it seems like a great idea . I was trying to test the same and get it running based on the commands in the README file but i was getting a bunch of errors when i was compiling the deploy.js file.

It'd be great if you can help me out with the same..

Thanks,
Raj

**Comment by BasharAG** [comment]
Same here. After running the deploy.js file, I got this error:

```
node build/ContratDepoloy.js
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/Tribe_Exchange-TX/build/ContratDepoloy.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
```

**Comment by seanavery** [comment]
@cyrus19901 @BasharAG Hey guys, I have not been maintaining this repo. When I get the time, I will come back and clean it up. This was an experiment using a entirely "on-chain" approach to providing a double auction from ERC20 token <--> Ether. I am now focusing more on off-chain approaches and facilitating liquidity ERC20 <--> ERC20. My email is seanpollock3344@gmail.com -- feel free to message me via gchat!
